name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  frontendTests:
    runs-on: ubuntu-latest
    name: JavaScript
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install Node dependencies
        run: npm install
        - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, intl, gd, xml, sqlite
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest --no-scripts
      - name: Run tests
        run: npm run test
